### ISSUE TITLE
Hyper-parameters for reproducing

### ISSUE THREAD

**Issue by YawYoung** [zlinao/MinTL#1]
Hello, thanks for your amazing work ^-^
I tried to reproduce your experiment result shown in paper, using the `end-2-end` setting shown in [run.py](https://github.com/zlinao/MinTL/blob/master/run.py)
![image](https://user-images.githubusercontent.com/57999348/98755909-70733680-2404-11eb-9891-4b8b54b4a042.png)
The result I got is about 3 point lower than the result in paper.
I followed [run.py](https://github.com/zlinao/MinTL/blob/master/run.py#L5) to run my experiment.
I use python3.6, 1 * V100, transformers==2.8.0, the other python packages are the same as [requirements.txt](https://github.com/zlinao/MinTL/blob/master/requirements.txt)

**Comment by zlinao** [comment]
Hi, the hyper-parameters should be the same in this repo. We tried random seeds 557, 558, 559 in our experiments.

**Comment by YawYoung** [comment]
Thx!
