### ISSUE TITLE
Evaluation and dialog state

### ISSUE THREAD

**Issue by Tomiinek** [zlinao/MinTL#2]
Hi, first thank you for your work!

I am trying to understand the way you evaluate models (especially the inform and success rates on MultiWOZ) when using the MinTL framework. For generating a response, the model has to encode the previous dialogue state and the context, and predict the state update which is combined with the original state to form a new one. This new dialog state is used for querying the database etc., right?

During the evaluation ([these lines?](https://github.com/zlinao/MinTL/blob/a527e01cd2ea2c64342f7dd7dea08be69dac2bdc/train.py#L169-L190)), is the model given the ground truth belief state from the previous turn, or does it use the "cummulative" one that was predicted in the previous turns of the particular conversation?

I see some problems in both cases. When using the ground-truth belief state from the previous turn, the metrics might be overestimated. On the other hand, when using the fully-predicted last state, the ground-truth user response is used and it might not be consistent with the previous state. So I would actually expect the metrics to be underestimated, am I right?  

Thank you in advance :slightly_smiling_face:

**Comment by zlinao** [comment]
Hi, thanks for interested in our work.

We use the ground truth belief state in the training time, and for the evaluation, we always use the fully-predicted last state.

**Comment by Tomiinek** [comment]
Cool, thank you for your prompt response!
